import json
ev=json.load(open('analysis/events_out.json'))
pri={'CUT':3,'HIT':2,'STAG':1,'MOVE':0}
acc=[(0.0,0.0,'start'),(84.867,84.867,'end')]
rej=[]
def ok(o,tg,lst):
    pts=sorted(lst+[(o,tg,'?')])
    for (a,b,_),(c,d,_) in zip(pts,pts[1:]):
        if not (c>a+1e-4 and d>b+1e-4): return False
        r=(d-b)/(c-a)
        if r<0.33 or r>4.0: return False
    return True
for e in sorted(ev,key=lambda e:(-pri[e['type']],e['t'])):
    if e['id'] in ('F30',): continue
    if ok(e['t'],e['target'],acc): acc.append((e['t'],e['target'],e['id']))
    else: rej.append(e['id'])
acc.sort()
print('anchors',len(acc),'rejected',rej)
T={e['id']:e['target'] for e in ev}
O={e['id']:e['t'] for e in ev}
js="// generated by tools/make_timeline.py from analysis/events_out.json\n"
js+="const WARP="+json.dumps([[round(tg,4),round(o,4)] for o,tg,_ in acc])+";\n"
js+="const TGT="+json.dumps(T)+";\nconst SRC="+json.dumps(O)+";\n"
open('src/timeline.js','w').write(js)
