"""Minimum-curvature time warp: rebuild time t -> source time s.
Hard anchors (cuts, hits) are met exactly; moves/ripples are soft targets.
Minimises sum of squared second differences on a 1/120 s grid -> C2-smooth speed."""
import json, numpy as np, scipy.sparse as sp, scipy.sparse.linalg as spl
ev = json.load(open('analysis/events_out.json'))
DUR = 84.867; h = 1 / 120; N = int(round(DUR / h)); T = np.arange(N + 1) * h
pri = {'CUT': 3, 'HIT': 2, 'STAG': 1, 'MOVE': 0}
hard = [(0.0, 0.0), (DUR, DUR)]; soft = []
# keep the same monotone anchor selection as before, then split hard / soft
acc = [(0.0, 0.0, 'start', 'CUT'), (DUR, DUR, 'end', 'CUT')]
def ok(o, tg, lst):
    pts = sorted(lst + [(o, tg, '?', '?')])
    for (a, b, _, _), (c, d, _, _) in zip(pts, pts[1:]):
        if not (c > a + 1e-4 and d > b + 1e-4): return False
        r = (d - b) / (c - a)
        if r < 0.33 or r > 4.0: return False
    return True
for e in sorted(ev, key=lambda e: (-pri[e['type']], e['t'])):
    if e['id'] == 'F30': continue
    if ok(e['t'], e['target'], acc): acc.append((e['t'], e['target'], e['id'], e['type']))
for o, tg, i, ty in acc:
    if i in ('start', 'end'): continue
    e = next(x for x in ev if x['id'] == i)
    isClick = 'CLICK' in e['what']
    (hard if ty == 'CUT' else soft).append((tg, o))
def row(t):  # linear interpolation weights on the grid
    k = min(N - 1, int(t / h)); f = t / h - k
    r = np.zeros(N + 1); r[k] = 1 - f; r[k + 1] = f; return r
import osqp
vmin, vmax = 0.5, 2.3
# objective (OSQP minimises 1/2 x'Px + q'x):
#   alpha * sum(dv^2)            dv = speed change per grid step = D2 w / h
# + lam   * sum((v - 1)^2)       v  = D1 w / h  (stay near real time)
# + mu    * sum((Rs w - ys)^2)   soft anchors (seconds)
D2 = sp.diags([1.0, -2.0, 1.0], [0, 1, 2], shape=(N - 1, N + 1))
D1 = sp.diags([-1.0, 1.0], [0, 1], shape=(N, N + 1))
alpha, lam, mu = 1.0, 2e-6, 0.25
Rs = sp.csc_matrix(np.array([row(t) for t, _ in soft])); ys = np.array([s for _, s in soft])
P = 2 * (alpha * (D2.T @ D2) / h**2 + lam * (D1.T @ D1) / h**2 + mu * (Rs.T @ Rs))
q = -2 * (lam * (D1.T @ np.ones(N)) / h + mu * (Rs.T @ ys))
Rh = sp.csc_matrix(np.array([row(t) for t, _ in hard])); yh = np.array([s for _, s in hard])
A = sp.vstack([Rh, D1]).tocsc()
l = np.concatenate([yh, np.full(N, vmin * h)]); u = np.concatenate([yh, np.full(N, vmax * h)])
m = osqp.OSQP()
m.setup(P=sp.csc_matrix(P), q=q, A=A, l=l, u=u, verbose=False, eps_abs=1e-7, eps_rel=1e-7, max_iter=400000, polish=True)
r = m.solve(); print('osqp status', r.info.status)
w = r.x
v = np.diff(w) / h
print('hard', len(hard), 'soft', len(soft))
dv=np.abs(np.diff(v)); print('speed min/max', v.min().round(3), v.max().round(3), ' max speed change per 1/120s', dv.max().round(4), 'at t=', round(dv.argmax()/120,3), ' p99', np.percentile(dv,99).round(4))
assert v.min() > 0.2, 'warp not monotone'
print('hard anchor max error ms', (np.abs(Rh @ w - yh).max()*1000).round(3))
# soft deviations in rebuild time (how far each soft event lands from its beat)
dev = []
for t, s in soft:
    tt = np.interp(s, w, T); dev.append((abs(tt - t) * 1000, t))
dev.sort(reverse=True)
print('soft-anchor deviations: median %.0f ms, max %.0f ms' % (np.median([d for d,_ in dev]), dev[0][0]))
print('worst:', [(round(d), round(t, 3)) for d, t in dev[:8]])
js = "// generated by tools/smooth_warp.py: minimum-curvature warp, rebuild t -> source s, step 1/120 s\n"
js += f"const WARP_STEP = {h};\nconst WARP_S = {json.dumps([round(x, 5) for x in w.tolist()])};\n"
old = open('src/timeline.js').read()
keep = old[old.index('const TGT='):]
open('src/timeline.js', 'w').write(js + keep)
np.save('analysis/warp_speed.npy', v)
